# Generated by Django 3.2.7 on 2022-01-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_position', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
