# Generated by Django 3.2.7 on 2021-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_editorfile_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorfile',
            old_name='name',
            new_name='document_name',
        ),
        migrations.AddField(
            model_name='editorfile',
            name='external_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='external_wf_step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='internal_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='internal_wf_step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='update_time',
            field=models.DateField(null=True),
        ),
    ]
