# Generated by Django 3.2.7 on 2021-12-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_document_created_by'),
        ('editor', '0004_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocTypeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.documenttype')),
                ('questions', models.ManyToManyField(to='editor.Questions')),
            ],
        ),
    ]
