# Generated by Django 3.2.7 on 2021-12-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_document_created_by'),
        ('editor', '0005_doctypequestions_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='questions',
            field=models.ManyToManyField(to='editor.Questions'),
        ),
        migrations.AlterField(
            model_name='template',
            name='document_type',
            field=models.OneToOneField(default=44, on_delete=django.db.models.deletion.CASCADE, to='workflow.documenttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocTypeQuestions',
        ),
    ]
