# Generated by Django 3.2.7 on 2021-12-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20211209_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
