# Generated by Django 3.2.7 on 2021-12-14 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0007_auto_20211213_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='auth_user_list',
            field=models.ManyToManyField(related_name='auth_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
