# Generated by Django 3.2.7 on 2021-12-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0008_template_auth_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
