# Generated by Django 3.2.7 on 2021-12-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_document_created_by'),
        ('editor', '0009_template_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.documenttype'),
        ),
    ]
