# Generated by Django 3.2.3 on 2022-02-07 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0010_alter_template_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorfile',
            name='reject_message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
