# Generated by Django 3.2.7 on 2022-06-22 07:30

from django.db import migrations, models
import editor.models_document


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20220207_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorfile',
            name='file',
            field=models.FileField(null=True, upload_to=editor.models_document.user_directory_path),
        ),
    ]
