# Generated by Django 3.2.7 on 2022-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='Anonymous', max_length=1000000),
        ),
    ]
