# Generated by Django 3.2.3 on 2022-02-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0002_document_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0011_auto_20220207_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizationv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(related_name='org_members', to=settings.AUTH_USER_MODEL)),
                ('organization_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_lead', to=settings.AUTH_USER_MODEL)),
                ('templates', models.ManyToManyField(to='editor.Template')),
                ('workflows', models.ManyToManyField(to='workflow.DocumentType')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_position', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_organization', to='organizationv2.organizationv2')),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
