# Generated by Django 3.2.3 on 2022-02-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationv2',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizationv2.company'),
        ),
    ]
