# Generated by Django 4.0.2 on 2022-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0003_company_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationv2',
            name='projects',
            field=models.ManyToManyField(related_name='org_projects', to='organizationv2.Project'),
        ),
    ]
