# Generated by Django 4.0.2 on 2022-02-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0004_organizationv2_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationtoken',
            old_name='org_id',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user_position',
        ),
    ]
