# Generated by Django 3.2.3 on 2022-02-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0005_company_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationtoken',
            old_name='org_id',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user_position',
        ),
    ]
