# Generated by Django 3.2.7 on 2022-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0008_alter_organizationv2_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(null=True, upload_to='logos_company/'),
        ),
    ]
