# Generated by Django 3.2.7 on 2022-03-21 08:13

from django.db import migrations, models
import organizationv2.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationv2', '0009_company_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='company',
            name='uploaded_company_logo',
            field=models.FileField(default='logo.png', null=True, upload_to=organizationv2.models.company_logo_path),
        ),
    ]
