# Generated by Django 3.2.7 on 2022-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20220207_0729'),
        ('organizationv2', '0011_alter_company_uploaded_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='documents',
            field=models.ManyToManyField(related_name='company_documents', to='editor.EditorFile'),
        ),
    ]
