# Generated by Django 3.2.7 on 2022-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_alter_editorfile_file'),
        ('organizationv2', '0012_company_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='templates',
            field=models.ManyToManyField(related_name='project_templates', to='editor.Template'),
        ),
    ]
