# Generated by Django 4.0.2 on 2022-02-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_document_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='external_work_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_external_wf', to='workflow.workflowmodel'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='internal_work_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_internal_wf', to='workflow.workflowmodel'),
        ),
    ]
